server:
  port: ${PORT:8080}

spring:
  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/aula}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql